# The Solver for Automated Generation of Benders-Like Cuts within Benders-Like Decomposition Using Lagrangian Cuts

"""
    solve_with_BlCLag!(inst::Instance, param::BlCLagparam)

Solve the Bilevel problem using Benders-like decomposition. 
For Benders-like cuts, they are generated by solving the corresponding lagrangian dual problem. 

# Arguments
- 'inst::Instance': The problem instance including the master and the subproblems.
- 'param::BlCLagparam': Parameters
"""
function solve_with_BlCLag!(inst::Instance, param::BlCLagparam)
    master = inst.master
    subs = inst.subproblems

    # register solver
    @debug "Starting setup of the GBC solver."
    new_stat!(param.stats, "Solver", "BlCLagSolver")
    new_stat!(param.stats, "time_limit", param.runtime)
    new_stat!(param.stats, "NSub", length(subs))
    new_stat!(param.stats, "BlCLagCuts", 0)
    new_stat!(param.stats, "SepaTime", 0)  # time spend in separator
    new_stat!(param.stats, "SepaTimeCut", 0)  # time spend in separator for generating cuts only

    # do some initail checks for master and sub solvers
    @debug "Doing some checks if master and sub were created correctly."
    check(master, param)
    for sub in subs
        check(sub, param)
    end

    # add subObj variables, one for each sub_problem, to the master, and add them to objective
    @debug "Start with initialization of BlCLagSolver."
    names = [name(sub) for sub in subs]
    subObj = @variable(master.model, subObj[names])
    for name in names
        @constraint(master.model, subObj[name] == inst.master.second_level_obj[name], base_name="L2obj_$(name)")
    end

    # debbug output
    try
        write_to_file(
            master.model,
            param.output_folder_path * "/master.$(param.file_format_output)",
        )
        set_optimizer_attribute(master.model, "LogFile", param.output_folder_path*"/blclag_mip_log.txt")
    catch err 
        @error "In BlCLagSolver, could not write model to file or set log file for folder $(param.output_folder_path). Error is $err"
    end

    # build the sub LPs for Benders subroutine 
    clps, runtime_init = init_connectorLPBlCs(subs, master.link_vars, param) 
    new_stat!(param.stats, "runtime_preprocessingGBC", runtime_init)

    # set time limit and number of threads
    true_runtime = param.runtime - runtime_init
    set_time_limit_sec(master.model, true_runtime)
    set_attribute(master.model, MOI.NumberOfThreads(), param.threads_master)
    for sub in subs
        set_nthreads(sub, param.threads_sub_con)
    end

    # add callback to master and solve 
    msol_cuts_mapping = Dict()  # a mapping of master solution to found lazy constraints
    @debug "Finished model construction. Now proceeding to optimization process by solving using BlC with Langrangian cut coef. Remaining runtime is $true_runtime"
    set_attribute(master.model, MOI.LazyConstraintCallback(), cb -> blclag_callback_function(cb, master, names, clps, subObj, msol_cuts_mapping, param))

    try 
        optimize!(master.model)
    catch e
        if (e isa TimeoutException)
            @warn "We run into a timeout when solving a Submodel with BlCLagSolver. Note that this implies that the Subproblem run for the time passed by timelimit and did not terminate. "
            new_stat!(param.stats, "BlCLagStatus", "Timeout_Submodel")
        else
            @error "BlCLagSolver suffered an error: $e"
            @error stacktrace(catch_backtrace())
            #showerror(stdout, e, catch_backtrace())
            new_stat!(param.stats, "BlCLagStatus", "Terminate")
            #rethrow(e) 
        end
    else
        # print solution and collected data
        print_collected_cuts(param, msol_cuts_mapping)
        if termination_status(master.model) == MOI.OPTIMAL || termination_status(master.model) == MOI.LOCALLY_SOLVED || termination_status(master.model) == MOI.TIME_LIMIT
            if primal_status(master.model) == MOI.FEASIBLE_POINT
                mobj = objective_value(master.model)
                xsol = Dict(a => value(master.link_vars[a]) for a in master.A)
                @debug "The master objective is $(mobj) and solution is $(xsol)."
                print_solution_to_file(mobj, xsol, param)
                new_stat!(param.stats, "Opt", mobj)

                # print full MIP solution to file
                solution = Dict(JuMP.name(x) => JuMP.value(x) for x in all_variables(master.model))
                write(param.output_folder_path*"/full_master_solution.json", JSON.json(solution))
            end

            # set status 
            status = termination_status(master.model)
            set_optimization_status_stats(status, param)
        else 
            @debug "The master MIP in BlCLagSolver is infeasible with termination status: $(termination_status(master.model))"
            set_optimization_status_stats(termination_status(master.model), param)
        end
        
        # save run data to statistics
        new_stat!(param.stats, "runtime", solve_time(master.model))
        new_stat!(param.stats, "gap", JuMP.relative_gap(master.model))
        new_stat!(param.stats, "BNodes", MOI.get(master.model, MOI.NodeCount()))
    end
end


"""
    init_connectorLPs(subs, link_vars, param)

Init all the ConnectorLP instances. 

# Return 
    - The build list of ConnectorLP objects
    - The overall time needed to init all ConnectorLP. In case of time out return 'param.runtime'.
"""
function init_connectorLPBlCs(subs, link_vars, param::BlCLagparam) 
    @debug "Beginn building LPs for each subproblems required for Benders steps."
    connectors = []
    time_s = @elapsed for s in subs
        con = ConnectorLP_BlC(param, s.A, link_vars, s)
        push!(connectors, con)
    end
    return connectors, time_s
end


function blclag_callback_function(cb_data, master::BlCLagMaster, sub_names, clps, subObj, msol_cuts_mapping::Dict, parameter::BlCLagparam)
    # x are the linking variables and clps the connectorLP_BlC (one for each sub)
    # subObj are the obj. vars. in master (for each sub)

    status = callback_node_status(cb_data, master.model)
    if status == MOI.CALLBACK_NODE_STATUS_FRACTIONAL
        # We currently do not support the separation of fractional BLCs
        return
    elseif status == MOI.CALLBACK_NODE_STATUS_INTEGER
        # I would just like to mention that @belapsed does not work (as I cannot pass global vars into the scope...)
        sepatime = @elapsed begin
            # `callback_value(cb_data, x)` is integer (to some tolerance).
            subObj_val = Dict(
                name => callback_value(cb_data, subObj[name]) for name in sub_names
            )
            @debug "Current values of the sub objectives are $(subObj_val)"
            x_vals = Dict(
                a => callback_value(cb_data, master.link_vars[a]) for a in master.A
            )
            round_master_solution(x_vals) # round to integer
            @debug "Current values of the master linking variables are $(x_vals)"
            lazy = []

            # Because of multi thread (and some start trouble I cannot explain) we resolve the subproblems for same master solution multiple times. 
            # To avoid this, we save the found cuts for each master solution and fall back on them before resolving the sub_problem
            msolkey = key_master_sol(x_vals, master.A)
            #@debug "The current master_key=$(msolkey) and the saved solutions are $(msol_cuts_mapping).")
            if haskey(msol_cuts_mapping, msolkey)
                # if we already solved this sub_problem, we just recover the list of found lazy constraints 
                lazy = msol_cuts_mapping[msolkey]
                @debug "We recovered the lazy cuts for solution $(x_vals) without resolving subproblems."
            else
                # solve each sub and add cut to list of cuts "lazy"
                @debug "We found no saved lazy cuts for current solution and solve subproblems now."
                for con in clps
                    cuttime = @elapsed begin
                        # solve corresponding connectorLP
                        ## there does not seem to be an easy way to obtain the remaining runtime in solver-independent callbacks. So we stick with a worst case approximation for the time limit.
                        cut=nothing
                        pobj=-1
                        cut, pobj, _ = genBenderslike_cut!(con, x_vals, parameter, parameter.runtime)
                        # in case of timeout within one subsolver, one of the Submodels run for timelimit time. We let this result in a timeout error 

                        # generate cut from found solution and add it to master if it cuts of current solution
                        if subObj_val[name(con)] - 1e-6 > pobj  # TODO: again, hard coded numeric
                            cutopt = @build_constraint( subObj[name(con)] <= cut)
                            @debug "Adding BlC cut $(cutopt) generated from Lagrangian dual to the master problem for sub $(name(con.sub_solver))."
                            add_stat!(parameter.stats, "BlCLagCuts", 1)
                            push!(lazy, cutopt)
                        else
                            @debug "No cut generated from Lagrangian dual to the master problem for sub $(name(con.sub_solver)) as current L2obj=$(subObj_val[name(con)]) and cut value=$pobj."
                        end
                    end
                    add_stat!(parameter.stats, "SepaTimeCut", cuttime)
                end

                # save that we found lazy const. for this sol
                msol_cuts_mapping[msolkey] = lazy
            end

            # add lazy cuts to master model
            map(cu -> MOI.submit(master.model, MOI.LazyConstraint(cb_data), cu), lazy)

            # output cuts to file in case of debbug mode
            if should_debbug_print(parameter)
                outfilecut = parameter.output_folder_path * "/mastercuts_last_update.txt"
                append_constraintlist_to_file(lazy, outfilecut)
            end
        end
        add_stat!(parameter.stats, "SepaTime", sepatime)
    else
        @assert status == MOI.CALLBACK_NODE_STATUS_UNKNOWN
        return
    end
end


