# The master problem in the Benders-like cuts model is where the big Ms are generated by solving the corresponding Lagrangian dual


struct BlCLagMaster{T}
    model::JuMP.Model  # The master problem without second level
    A::Vector{T}  # Iterable of common resources
    link_vars::Dict{T,VariableRef}  # Linking variables as dict. Keys=A
    sub_names::Vector{String}  # List of sub_problem names

    second_level_obj::Dict{String, <:JuMP.AbstractJuMPScalar}  # name subproblem -> the second level objective function (stated in the HPR variables)
end 


"""
    check(master::Master, params::SolverParam)

Check the master problem for consistency and correctness.
"""
function check(master::BlCLagMaster, params::BlCLagparam)
    # We need one linking variable for each resource
    if !(length(master.A) == length(master.link_vars))
        error(
            "You need to provide the same number of master linking variables as there are resources. |A| = $(length(master.A)) but |vars| = $(length(master.link_vars)).",
        )
    end

    # Check that linking variables are in the master problem
    for a in master.A
        if !is_valid(master.model, master.link_vars[a])
            error(
                "In the master problem, there is no linking variable for resource $(a) in the master JuMP model.",
            )
        end
    end
end

